In [2]:
## checking how numpy is better than list
import numpy as np
import time 
import sys
s = range(100)
print(sys.getsizeof(1))           # Return the size of one element of an array
print(len(s))                     # Returns the total number of elements in an array
print(sys.getsizeof(5)*len(s))    

28
100
2800


In [9]:
d = np.arange(100)
print(d.size)                     #  Return total number of elements of an array.
print(d.itemsize)                 #  Return the size in bytes of each element of an array.
print(d.size*d.itemsize)          #  space occupied by one element multiplied by total number of elements in an array will
                                  #   give total space occupied.


100
4
400


In [38]:
size = 10000000000
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x,y) for x,y in zip(l1,l2)]
# print(result)
print("time taken",(time.time()-start)*1000)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
time taken 1.0001659393310547


In [65]:
a1 = np.arange(size)
a2 = np.arange(size)
result = a1+a2
print(result)
print((time.time()-start)*1000)


ValueError: Maximum allowed size exceeded

In [15]:
import numpy as np
a = np.arange(100).reshape(10,10)
print(a)



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [17]:
print(a[0][2])

2


In [19]:
for x,y in len(a) :
    print(a[x][y])

TypeError: 'int' object is not iterable

In [42]:
for x in range(1 , 7):
    for j in range(1,21):
        if(x ==1 or x == 6 or j == 1 or j ==20):
            print("*",end="")            
        else : 
            print(" ", end="")   
    print()
          
     
  
    
    

********************
*                  *
*                  *
*                  *
*                  *
********************


In [14]:
a = np.arange(30).reshape(10,3)  #reshape(rows,columns)   for 2 dimensional array
print(a)
print("dimensions of a: ",a.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
dimensions of a:  2


In [19]:
a = np.arange(28).reshape(2,2,7)  #reshape(dimensions,rows,columns)  for 3 dimensional array
print(a)
print("dimensions of a : ",a.ndim)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]]
dimensions of a :  3


In [24]:
mydata = np.genfromtxt('C:/Users/mlangaru.OSIUS/Desktop/ing.csv',delimiter=',')
print(mydata) # doesn't read text and prints it as nan(not a number) and it takes numbers as float 

[[      nan       nan       nan       nan       nan       nan       nan
        nan       nan       nan       nan]
 [0.000e+00       nan       nan       nan       nan 9.000e+00       nan
        nan 2.012e+03 9.000e+00 1.200e+01]
 [1.000e+00       nan       nan       nan       nan 9.000e+00       nan
        nan 2.012e+03 9.000e+00 1.200e+01]
 [2.000e+00       nan       nan       nan       nan 8.500e+00       nan
        nan 2.012e+03 9.000e+00 1.200e+01]
 [3.000e+00       nan       nan       nan       nan 8.500e+00       nan
        nan 2.012e+03 9.000e+00 1.100e+01]]


In [28]:
mydata = np.genfromtxt('C:/Users/mlangaru.OSIUS/Desktop/ing.csv',delimiter = ',' , dtype = 'int')
print(mydata)  # as it doesn't read string values it is displaying then as -1 as we gave dtype as int

[[  -1   -1   -1   -1   -1   -1   -1   -1   -1   -1   -1]
 [   0   -1   -1   -1   -1    9   -1   -1 2012    9   12]
 [   1   -1   -1   -1   -1    9   -1   -1 2012    9   12]
 [   2   -1   -1   -1   -1    8   -1   -1 2012    9   12]
 [   3   -1   -1   -1   -1    8   -1   -1 2012    9   11]]


In [31]:
mydata = np.genfromtxt('C:/Users/mlangaru.OSIUS/Desktop/ing.csv',delimiter = ',' , dtype = 'String')


TypeError: data type "t" not understood

In [37]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
print("addition of two arrays : ",a+b)
print("substraction of two arrays : ",a-b)


addition of two arrays :  [[ 0  2  4  6  8]
 [10 12 14 16 18]]
substraction of two arrays :  [[0 0 0 0 0]
 [0 0 0 0 0]]


In [41]:
print("division of two arrays : ", a / b)
print("multiplication of two arrays : ", a*b)
print(a % b)

division of two arrays :  [[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
multiplication of two arrays :  [[ 0  1  4  9 16]
 [25 36 49 64 81]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


c:\users\mlangaru.osius\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\mlangaru.osius\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in remainder
  This is separate from the ipykernel package so we can avoid doing imports until


In [43]:
print(a**b)

[[        1         1         4        27       256]
 [     3125     46656    823543  16777216 387420489]]


In [59]:

print(a.sum())

print(b.sum())
print(a.sum()+b.sum())

print(a.sum(axis=1))

print(a.sum(axis=0))
print(a)

45
45
90
[10 35]
[ 5  7  9 11 13]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [71]:
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())
print(b.min())
print(b.argmin())
print(b.max())
print(b.argmax())
print(a[1])
print(a[1][3])
print(b[0])
print(b[0][3])
print(b[0][:3])

0
0
9
9
0
0
9
9
[5 6 7 8 9]
8
[0 1 2 3 4]
3
[0 1 2]


In [73]:
print(a)
print(np.transpose(a))
print(a.ravel())   # it flattens the array into a single list

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[0 1 2 3 4 5 6 7 8 9]
